# Generated by Django 5.1.7 on 2025-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField()),
                ("instructions", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("retro", "Retro"),
                            ("arcade", "Arcade"),
                            ("puzzle", "Puzzle"),
                            ("action", "Action"),
                            ("strategy", "Strategy"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="games/thumbnails/"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
    ]
