# Generated by Django 5.1.7 on 2025-03-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = []
